services:
  - type: web
    name: indian-movie-recommender
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    autoDeploy: true
    plan: free
